services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-delivery-api
    environment:
      NODE_ENV: docker
      PORT: 3000
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: food_delivery
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin123
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - food-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: food-delivery-postgres
    environment:
      POSTGRES_DB: food_delivery
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d food_delivery"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - food-network

  redis:
    image: redis:7-alpine
    container_name: food-delivery-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - food-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: food-delivery-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - food-network

networks:
  food-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
